### ISSUE TITLE
Design of the car details webpage

### ISSUE THREAD

**Issue by rdugg4** [rdugg4/IFB299-Group-70-S.K.R.A.M#15]

**Comment by shaleenchantelle** [comment]
![image](https://user-images.githubusercontent.com/41880540/45080412-375e1e00-b138-11e8-8c22-1ff398c997e8.png)

**Comment by shaleenchantelle** [comment]
![image](https://user-images.githubusercontent.com/41880540/45149373-b6248b00-b20c-11e8-883f-7710f27d77ca.png)
