### ISSUE TITLE
Design a search results page

### ISSUE THREAD

**Issue by rdugg4** [rdugg4/IFB299-Group-70-S.K.R.A.M#19]

**Comment by shaleenchantelle** [comment]
[Car search results page.pptx](https://github.com/rdugg4/IFB299-Group-70-S.K.R.A.M/files/2356255/Car.search.results.page.pptx)

**Comment by shaleenchantelle** [comment]
![image](https://user-images.githubusercontent.com/41880540/45146166-abb2c300-b205-11e8-8dba-af7f699ee0e7.png)

**Comment by shaleenchantelle** [comment]
![image](https://user-images.githubusercontent.com/41880540/45149304-92614500-b20c-11e8-8111-8b39a90104ee.png)
