### ISSUE TITLE
Design the create account webpage

### ISSUE THREAD

**Issue by rdugg4** [rdugg4/IFB299-Group-70-S.K.R.A.M#44]

**Comment by shaleenchantelle** [comment]
Design is completed. Just unsure where to upload

**Comment by shaleenchantelle** [comment]
[Create Customer Account design.pptx](https://github.com/rdugg4/IFB299-Group-70-S.K.R.A.M/files/2351866/Create.Customer.Account.design.pptx)

**Comment by shaleenchantelle** [comment]
![image](https://user-images.githubusercontent.com/41880540/45080592-8c9a2f80-b138-11e8-81dc-e7c82f0b1d97.png)
